import * as cdk from "aws-cdk-lib";
import * as eks from "aws-cdk-lib/aws-eks";
import * as iam from "aws-cdk-lib/aws-iam";
import * as secretsmanager from "aws-cdk-lib/aws-secretsmanager";
import { Construct } from "constructs";
import { config } from "./config";

export interface SecretsStackProps extends cdk.StackProps {
  /** Cluster name, used to scope Pod Identity associations + the addon. */
  readonly clusterName: string;
}

/**
 * SecretsStack — application secrets in AWS Secrets Manager, surfaced into the
 * cluster by the AWS Secrets Store CSI Driver.
 *
 * Passwords are generated by Secrets Manager (never hardcoded in git). The
 * Secrets Store CSI Driver's AWS provider (an EKS managed add-on) reads them
 * using EKS Pod Identity and syncs them into Kubernetes Secrets that Keycloak
 * and Postgres consume as environment variables.
 *
 * The CSI provider assumes the *consuming pod's* identity, so the IAM role is
 * associated with the workload service accounts (keycloak, postgres) rather
 * than a controller service account.
 *
 * Secret JSON shape (key "password"):
 *   <prefix>/keycloak/admin     -> { "password": <generated> }
 *   <prefix>/keycloak/postgres  -> { "password": <generated> }
 */
export class SecretsStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props: SecretsStackProps) {
    super(scope, id, props);

    const makePassword = (id: string, name: string) =>
      new secretsmanager.Secret(this, id, {
        secretName: name,
        description: `Generated password for ${name}`,
        generateSecretString: {
          secretStringTemplate: JSON.stringify({}),
          generateStringKey: "password",
          passwordLength: 24,
          // Exclude characters that are awkward in URLs / shell / JDBC.
          excludePunctuation: true,
          excludeCharacters: '"@/\\',
        },
      });

    makePassword("KeycloakAdminSecret", `${config.prefix}/keycloak/admin`);
    makePassword("KeycloakPostgresSecret", `${config.prefix}/keycloak/postgres`);

    // Shared role the CSI provider assumes (via Pod Identity) to read secrets.
    // Trust principal pods.eks.amazonaws.com with AssumeRole + TagSession;
    // read access limited to secrets under the project prefix.
    const secretsReaderRole = new iam.Role(this, "SecretsReaderRole", {
      roleName: `${config.prefix}-secrets-reader-role`,
      assumedBy: new iam.ServicePrincipal("pods.eks.amazonaws.com"),
      description: "Read access to Secrets Manager for CSI-mounting workloads",
    });
    (secretsReaderRole.assumeRolePolicy as iam.PolicyDocument).addStatements(
      new iam.PolicyStatement({
        effect: iam.Effect.ALLOW,
        principals: [new iam.ServicePrincipal("pods.eks.amazonaws.com")],
        actions: ["sts:TagSession"],
      }),
    );
    secretsReaderRole.addToPolicy(
      new iam.PolicyStatement({
        effect: iam.Effect.ALLOW,
        actions: [
          "secretsmanager:GetSecretValue",
          "secretsmanager:DescribeSecret",
        ],
        resources: [
          `arn:aws:secretsmanager:${this.region}:${this.account}:secret:${config.prefix}/*`,
        ],
      }),
    );

    // Associate the reader role with the workload service accounts that mount
    // the CSI volume. The AWS CSI provider exchanges the pod's identity for
    // this role when fetching secrets.
    for (const sa of ["keycloak", "postgres"]) {
      new eks.CfnPodIdentityAssociation(this, `PodIdentity-${sa}`, {
        clusterName: props.clusterName,
        namespace: "keycloak",
        serviceAccount: sa,
        roleArn: secretsReaderRole.roleArn,
      });
    }

    // AWS Secrets Manager provider for the Secrets Store CSI Driver (managed
    // add-on). This add-on bundles the upstream core driver as a dependency,
    // so no separate Helm install is needed. The core driver's syncSecret
    // feature (OFF by default) must be enabled here for `secretObjects` to
    // create Kubernetes Secrets; secret rotation is enabled so synced values
    // refresh when the source secret changes.
    new eks.CfnAddon(this, "SecretsStoreCsiProvider", {
      clusterName: props.clusterName,
      addonName: "aws-secrets-store-csi-driver-provider",
      resolveConflicts: "OVERWRITE",
      configurationValues: JSON.stringify({
        "secrets-store-csi-driver": {
          syncSecret: { enabled: true },
          enableSecretRotation: true,
        },
      }),
    });
  }
}
